<?php
/** @var \MageSuite\PwaNotifications\Helper\Configuration $helper */
$helper = $block->getConfigurationHelper();
$jsConfig = $block->getJsConfig();
$jsConfig['applicationServerKey'] = $helper->getServerPublicKey();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "notification-panel": {
                        "component": "MageSuite_PwaNotifications/js/notification-panel",
                        "config": <?= /* @noEscape */  json_encode($jsConfig) ?>
                    }
                }
            }
        }
    }
</script>
