<div class="cs-pwa-notification-panel cs-pwa-notification-panel--request">
    <div class="cs-pwa-notification-panel__wrapper">
        <div class="cs-pwa-notification-panel__icon-wrapper">
        <?= $block->getChildHtml('pwa.notification.panel.icon.request'); ?>
        <?= $block->getChildHtml('pwa.notification.panel.icon.browser'); ?>
        <?= $block->getChildHtml('pwa.notification.panel.icon.enabled'); ?>
        </div>
        <div class="cs-pwa-notification-panel__message-wrapper">
            <div class="cs-pwa-notification-panel__message cs-pwa-notification-panel__message--request">
                <span class="cs-pwa-notification-panel__message-title"><?= /* @noEscape */ $block->getNotificationsEnableTitle(); ?></span>
                <span class="cs-pwa-notification-panel__message-description"><?= /* @noEscape */ $block->getNotificationsEnableDescription(); ?></span>
            </div>
            <div class="cs-pwa-notification-panel__message cs-pwa-notification-panel__message--browser">
                <span class="cs-pwa-notification-panel__message-title"><?= /* @noEscape */ $block->getNotificationsBrowserTitle(); ?></span>
                <span class="cs-pwa-notification-panel__message-description"><?= /* @noEscape */ $block->getNotificationsBrowserDescription(); ?></span>
            </div>
            <div class="cs-pwa-notification-panel__message cs-pwa-notification-panel__message--enabled">
                <span class="cs-pwa-notification-panel__message-title"><?= /* @noEscape */ $block->getNotificationsEnabledTitle(); ?></span>
                <span class="cs-pwa-notification-panel__message-description"><?= /* @noEscape */ $block->getNotificationsEnabledDescription(); ?></span>
            </div>
        </div>
        <div class="cs-pwa-notification-panel__actions">
            <div class="cs-pwa-notification-panel__action cs-pwa-notification-panel__action--request">
                <button class="cs-pwa-notification-panel__button cs-pwa-notification-panel__button--accept">
                    <span class="cs-pwa-notification-panel__button-span"><?= /* @noEscape */ $block->getButtonAcceptText(); ?></span>
                    <?= $block->getChildHtml('pwa.notification.panel.button.accept.icon'); ?>
                </button>
                <button class="cs-pwa-notification-panel__button cs-pwa-notification-panel__button--decline">
                    <span class="cs-pwa-notification-panel__button-span"><?= /* @noEscape */ $block->getButtonDeclineText(); ?></span>
                    <?= $block->getChildHtml('pwa.notification.panel.button.decline.icon'); ?>
                </button>
            </div>
            <div class="cs-pwa-notification-panel__action cs-pwa-notification-panel__action--browser">
                <div class="cs-pwa-notification-panel__permission">
                    <span class="cs-pwa-notification-panel__permission-title">
                        <?= /* @noEscape */ sprintf(__('%s wants to:'), $block->getBaseUrl()); ?>
                    </span>
                    <span class="cs-pwa-notification-panel__permission-title">
                        <?= $block->getChildHtml('pwa.notification.panel.permission.icon'); ?>
                        <?= /* @noEscape */ __('Display notifications'); ?>
                    </span>
                    <div class="cs-pwa-notification-panel__permission-button-wrapper">
                    <span class="cs-pwa-notification-panel__permission-button cs-pwa-notification-panel__permission-button--block">
                            <?= /* @noEscape */ __('Block'); ?>
                        </span>
                    <span class="cs-pwa-notification-panel__permission-button cs-pwa-notification-panel__permission-button--allow">
                            <?= /* @noEscape */ __('Allow'); ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <a href="#" class="cs-pwa-notification-panel__close">
            <?= $block->getChildHtml('pwa.notification.panel.close.icon'); ?>
        </a>
    </div>
</div>
