<?php
/** @var \MageSuite\PwaNotifications\Helper\Configuration $helper */
$helper = $block->getConfigurationHelper();
?>
<script type="text/x-magento-init">
{
    ".cs-pwa-notification-panel": {
        "MageSuite_PwaNotifications/js/notification": {
            "beforeTarget": "#maincontent",
            "applicationServerKey": "<?= /* @noEscape */ $helper->getServerPublicKey() ?>",
            "notificationType": "shipping",
            "notificationEnableDescription": "Would you like to be informed about the delivery status of your order via push notifications?",
            "notificationClosingTimeout": 5000,
            "notificationSubscribedDescription": "Thank you! You will be informed when you order is shipped"
        }
    }
}
</script>
