<div class="cs-push-notification__wrapper" data-bind="scope: 'push-notification'">
    <div class="cs-push-notification <?= $block->getModifier() ?>" data-bind="css: {'_active': showPanel}">
        <div class="cs-push-notification__content" data-bind="css: modifier">
            <?= $block->getChildHtml('push.notification.hotspot.before'); ?>
            <?php if ($block->getRenderIcons()) { ?>
                <div class="cs-push-notification__icons">
                    <div class="cs-push-notification__icon-wrapper cs-push-notification__icon-wrapper--request" data-bind="visible: subscriptionStatus() === 'request'">
                        <?= $block->getChildHtml('push.notification.icon.request'); ?>
                    </div>
                    <div class="cs-push-notification__icon-wrapper cs-push-notification__icon-wrapper--pending" data-bind="visible: subscriptionStatus() === 'pending'">
                        <?= $block->getChildHtml('push.notification.icon.pending'); ?>
                    </div>
                    <div class="cs-push-notification__icon-wrapper cs-push-notification__icon-wrapper--granted" data-bind="visible: subscriptionStatus() === 'granted'">
                        <?= $block->getChildHtml('push.notification.icon.enabled'); ?>
                    </div>
                    <div class="cs-push-notification__icon-wrapper cs-push-notification__icon-wrapper--rejected" data-bind="visible: subscriptionStatus() === 'rejected'">
                        <?= $block->getChildHtml('push.notification.icon.rejected'); ?>
                    </div>
                </div>
            <?php } ?>
            <div class="cs-push-notification__message-wrapper">
                <div class="cs-push-notification__message">
                    <span class="cs-push-notification__message-title" data-bind="text: content().header"></span>
                    <span class="cs-push-notification__message-description" data-bind="text: content().description"></span>
                </div>
            </div>
            <div class="cs-push-notification__actions" data-bind="visible: showActions">
                <button class="cs-push-notification__button cs-push-notification__button--accept" data-bind="click: onAccept">
                    <span class="cs-push-notification__button-span"><?= /* @noEscape */ $block->getButtonAcceptText(); ?></span>
                    <?= $block->getChildHtml('push-notification.button.accept.icon'); ?>
                </button>
                <?php if ($block->getShowDeclineButton()) { ?>
                    <button class="cs-push-notification__button cs-push-notification__button--decline" data-bind="click: closePanel">
                        <span class="cs-push-notification__button-span"><?= /* @noEscape */ $block->getButtonDeclineText(); ?></span>
                        <?= $block->getChildHtml('push.notification.button.decline.icon'); ?>
                    </button>
                <?php } ?>
            </div>
            <a href="#" class="cs-push-notification__close" data-bind="click: closePanel">
                <?= $block->getChildHtml('push.notification.close.icon'); ?>
            </a>
        </div>
        <?= $block->getChildHtml('push.notification.hotspot.after'); ?>
    </div>
</div>
