<?php
// phpcs:ignoreFile
// below code is only for BE testing purposes, will be refactored/changed by frontend developers
/** @var \MageSuite\Pwa\Block\Data $block */
/** @var \MageSuite\Pwa\Model\Data\ViewModel $viewModel */
$viewModel = $block->getViewModel();
$configuration = $viewModel->getConfiguration();
?>
<script>
    self.addEventListener('push', function (event) {
        var options = JSON.parse(event.data.text());
        var title = options['title'] === undefined || options['title'] === null ? '<?=$configuration->getName()?>' : options['title'];

        event.waitUntil(self.registration.showNotification(title, options));
    });

    self.addEventListener('notificationclick', function(e) {
        var notification = e.notification;
        var action = e.action;

        if (action === 'close') {
            notification.close();
        } else {
            if(
                notification.data !== undefined && notification.data !== null
                &&
                notification.data.url !== undefined && notification.data.url !== null
            ) {
                clients.openWindow(notification.data.url);
            }
            notification.close();
        }
    });
</script>
