<?php
// phpcs:ignoreFile
/** @var \MageSuite\Pwa\Block\Data $block */
/** @var \MageSuite\Pwa\Model\Data\ViewModel $viewModel */
$viewModel = $block->getViewModel();
$configuration = $viewModel->getConfiguration();
$deviceInformationApiUrl = sprintf('%srest/V1/pwa/device_information', $viewModel->getStoreBaseUrl());

?>
<script>
    self.addEventListener('push', function (event) {
        var options = JSON.parse(event.data.text());
        var title = options['title'] === undefined || options['title'] === null ? '<?=$configuration->getName()?>' : options['title'];

        if(options.icon === undefined) {
            options.icon = '<?= $block->getViewFileUrl('Magento_Theme::icon-512x512.png'); ?>';
        }

        if(options.badge === undefined) {
            options.badge = '<?= $block->getViewFileUrl('Magento_Theme::badge-72x72.png'); ?>';
        }

        event.waitUntil(self.registration.showNotification(title, options));
    });

    self.addEventListener('notificationclick', function(e) {
        var notification = e.notification;
        var action = e.action;

        if (action === 'close') {
            notification.close();
        } else {
            if(
                notification.data != null
                &&
                notification.data.url != null && notification.data.url !== ''
            ) {
                clients.openWindow(notification.data.url);
            }
            notification.close();
        }
    });

    self.addEventListener('pushsubscriptionchange', function (event) {
        if (event.oldSubscription && event.newSubscription) {
            event.waitUntil(
                fetch('<?=$deviceInformationApiUrl?>', {
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify({
                        oldEndpoint: event.oldSubscription.endpoint,
                        endpoint: event.newSubscription.endpoint,
                        keys: event.newSubscription.toJSON().keys
                    })
                })
            );
        }
    });
</script>
