<?php
// below code is only for BE testing purposes, will be refactored/changed by frontend developers
$helper = $this->helper(\MageSuite\PwaNotifications\Helper\Configuration::class);
?>
<script type="text/javascript">
    function urlBase64ToUint8Array(base64String) {
        var padding = '='.repeat((4 - base64String.length % 4) % 4);
        var base64 = (base64String + padding)
            .replace(/\-/g, '+')
            .replace(/_/g, '/');

        var rawData = window.atob(base64);
        var outputArray = new Uint8Array(rawData.length);

        for (var i = 0; i < rawData.length; ++i) {
            outputArray[i] = rawData.charCodeAt(i);
        }
        return outputArray;
    }

    function registerToPush() {
        navigator.serviceWorker.getRegistrations().then(
            function (registrations) {
                for (let registration of registrations) {
                    const subscribeOptions = {
                        userVisibleOnly: true,
                        applicationServerKey: urlBase64ToUint8Array(
                            '<?=$helper->getServerPublicKey()?>'
                        )
                    };

                    return registration.pushManager.subscribe(subscribeOptions);
                }
            }
        ).then(function (pushSubscription) {
            if(localStorage.getItem('pwa_device_identifier') !== undefined) {
                fetch('/rest/V1/pwa/device_information', {
                    method: 'POST',
                    body: JSON.stringify(pushSubscription),
                    headers: {
                        'Content-type': 'application/json; charset=UTF-8'
                    }
                })
                    .then(response => response.json())
                    .then(function (deviceIdentifier) {
                        localStorage.setItem('pwa_device_identifier', deviceIdentifier);
                        console.log(deviceIdentifier);
                    });
            }
        });
    }

    registerToPush();
</script>
